### ISSUE TITLE
Can not run the demo code

### ISSUE THREAD

**Issue by ly01325** [NVIDIA-Omniverse/iot-samples#2]
Hi, I am trying to run this sample. But I encounter an error when I following the script, Could you help me.?
My Environment:
Nucleus Service: 2023.1.0
USD Composer:2023.2.0
Kit:105.1.0

My install.bat log
![image](https://github.com/NVIDIA-Omniverse/iot-samples/assets/102361585/493bc5e4-9b50-4a7f-855e-266ba07ce0cc)
My link_app log
![image](https://github.com/NVIDIA-Omniverse/iot-samples/assets/102361585/d12f199b-729c-4986-bc7e-8a6ca023e28f)
my run_app.py log
Requirement already satisfied: pip in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (21.2.1+nv1)
Collecting pip
  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.1+nv1
    Uninstalling pip-21.2.1+nv1:
      Successfully uninstalled pip-21.2.1+nv1
  WARNING: The scripts pip.exe, pip3.10.exe, pip3.11.exe and pip3.exe are installed in 'C:\Users\liuy\Desktop\IOTSample\iot-samples-main\_build\target-deps\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.3.1
PS C:\Users\liuy\Desktop\IOTSample\iot-samples-main> python .\source\ingest_app_csv\run_app.py -u liuyang -p llll6yyyy
Requirement already satisfied: pandas in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from -r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: paho-mqtt in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from -r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from pandas->-r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from pandas->-r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from pandas->-r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from pandas->-r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (2023.3)
Requirement already satisfied: six>=1.5 in c:\packman-repo\chk\python\3.10.13+nv2-windows-x86_64\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r C:\Users\liuy\Desktop\IOTSample\iot-samples-main\requirements.txt (line 1)) (1.16.0)
---- LOG MESSAGES ---
('Main', 'nucleus_connection', LogLevel.VERBOSE, 'Connection library (version 0x000b001400000000, protocol version 1.19) settings:')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '  Transfer settings:')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    contentBufferSize = 1073741824')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    receiveBufferSize = 268435456')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    transmitBufferSize = 1073741824')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    maxTransferConnectionCount = 10')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    parallelTransferChunkSize = 1048576')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    lftContentBufferSize = 1073741824')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '  Log settings:')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    logFile = 1')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    logTickStatistics = 0')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    logIncomingMessages = 1')
('Main', 'nucleus_connection', LogLevel.VERBOSE, '    logOutgoingMessages = 1')
('Main', 'nucleus_connection', LogLevel.VERBOSE, 'OmniTrace dll/so not loaded')
('Main', 'provider_nucleus', LogLevel.INFO, 'Initialized Nucleus API v11.20-4c89d0de')
('Main', 'core', LogLevel.VERBOSE, 'Request 1: copy(file:C:\\Users\\liuy\\Desktop\\IOTSample\\iot-samples-main\\content/ConveyorBelt_A08_PR_NVD_01 => omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01)')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(localhost): Starting')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(wss://localhost/omni/discovery): Searching for services')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840DD00 connecting to wss://localhost/omni/discovery')
('Tick', 'idl', LogLevel.VERBOSE, 'connecting to wss://localhost:443/omni/discovery')
('Tick', 'idl', LogLevel.VERBOSE, '00000148EF10B930 not using mTLS since client certificate and private key were not provided')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=1 DiscoverySearch.find 00000148A8788998')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=2 DiscoverySearch.find 00000148A8786C58')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=3 DiscoverySearch.find 00000148A8785B78')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=4 DiscoverySearch.find 00000148A8787678')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost/omni/discovery): Searching for services')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840B910 connecting to ws://localhost/omni/discovery')
('Tick', 'idl', LogLevel.VERBOSE, 'connecting to ws://localhost:80/omni/discovery')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=1 DiscoverySearch.find 00000148A87878B8')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=2 DiscoverySearch.find 00000148A8786A18')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=3 DiscoverySearch.find 00000148A8786A18')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=4 DiscoverySearch.find 00000148A8785B78')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost:3333): Searching for services')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840CA40 connecting to ws://localhost:3333')
('Tick', 'idl', LogLevel.VERBOSE, 'connecting to ws://localhost:3333/')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=1 DiscoverySearch.find 00000148A8788AB8')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=2 DiscoverySearch.find 00000148A8785B78')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=3 DiscoverySearch.find 00000148A8788758')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=4 DiscoverySearch.find 00000148A8787D38')
('Tick', 'core', LogLevel.VERBOSE, 'Request 1: Stat(file:/C:/Users/liuy/Desktop/IOTSample/iot-samples-main/content/ConveyorBelt_A08_PR_NVD_01) returned Ok')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F183C0 remote server does not support WebSockets')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F183C0 Terminating connection (remote server does not support WebSockets)')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost/omni/discovery): Auth::Credentials search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost/omni/discovery): Auth::Tokens search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost/omni/discovery): Auth::DeviceFlow search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost/omni/discovery): Api::Connection search failed: Connection is terminated')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F183C0 Sending CLOSE (reason=1000)')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F1A640 Upgraded to WebSocket')
('Tick', 'idl', LogLevel.VERBOSE, '>> id=1 {"found": true, "version": 2, "service_interface": {"origin": "OmniAuth.idl.ts", "name": "Credentials", "capabilities": {"get_settings": 0, "auth": 1, "register": 1, "reset": 1}}, "transport": {"name": "sows", "params": "{\\"host\\": \\"127.0.0.1\\", \\"port\\": 3100}", "meta": {"marshaller": "bs", "serializer": "json", "ssl": "false"}}, "meta": {"deployment": "external", "version": "1.4.9+merge-requests/184.teamcity.1091.823ed169", "login_url": "http://*:3180"}}#')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost:3333): Found Auth::Credentials service using transport \'sows\' {"host": "127.0.0.1", "port": 3100}')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost:3333): Found auth login_url http://*:3180')
('Tick', 'idl', LogLevel.VERBOSE, '>> id=2 {"found": true, "version": 2, "service_interface": {"origin": "OmniAuth.idl.ts", "name": "Tokens", "capabilities": {"generate": 1, "refresh": 0, "subscribe": 0, "create_api_token": 1, "delete_api_token": 0, "get_api_tokens": 0, "auth_with_api_token": 0}}, "transport": {"name": "sows", "params": "{\\"host\\": \\"127.0.0.1\\", \\"port\\": 3100}", "meta": {"marshaller": "bs", "serializer": "json", "ssl": "false"}}, "meta": {"deployment": "external", "version": "1.4.9+merge-requests/184.teamcity.1091.823ed169", "login_url": "http://*:3180"}}#')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost:3333): Auth::Tokens found!')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost:3333): Auth::Tokens supports subscribe!')
('Tick', 'idl', LogLevel.VERBOSE, '>> id=3 {"found": false, "version": 2}#')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost:3333): Auth::DeviceFlow not found')
('Tick', 'idl', LogLevel.VERBOSE, '>> id=4 {"found": true, "version": 2, "service_interface": {"origin": "omni1.idl.ts", "name": "Connection", "capabilities": {"add_user_to_group": 0, "auth": 5, "authorize_token": 4, "change_acl": 0, "checkpoint_version": 2, "copy": 2, "copy2": 2, "create": 2, "create_asset": 2, "create_asset_with_hash": 2, "create_directory": 1, "create_group": 0, "create_object": 2, "deep_copy_object_struct": 0, "delete": 0, "delete2": 1, "get_acl": 0, "get_acl_resolved": 0, "get_acl_v2": 0, "get_branches": 1, "get_checkpoints": 1, "get_group_users": 0, "get_groups": 0, "get_mount_info": 0, "get_transaction_id": 0, "get_user_groups": 0, "get_users": 0, "list": 5, "list2": 
5, "lock": 3, "mount": 0, "ping": 0, "read": 2, "read_asset_resolved": 0, "read_asset_version": 0, "read_object_resolved": 0, "read_object_version": 0, "remove_group": 0, "remove_user_from_group": 0, "rename": 2, "rename2": 1, "rename_group": 0, "replace_version": 1, "service_resolve_acl": 2, "service_subscribe_list": 1, "set_acl_v2": 0, "set_path_options": 1, "set_path_options2": 0, "set_user_agent": 0, "stat2": 2, "subscribe_list": 4, "subscribe_read_asset": 2, "subscribe_read_object": 3, "subscribe_server_notifications": 0, "unlock": 2, "unmount": 0, "update": 1, "update_asset": 2, "update_asset_with_hash": 2, "update_object": 2, "stop": 0}}, "transport": {"name": "connlib", "params": "{\\n    \\"url\\": \\"ws://127.0.0.1:3009\\"\\n}", "meta": {}}, "meta": {"deployment": "external"}}#')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(ws://localhost:3333): Api::Connection found!')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(ws://localhost:3333): Found Nucleus API ws://127.0.0.1:3009')
('Tick', 'idl', LogLevel.VERBOSE, 'ssl send error: 10057')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F1F940 Terminating connection (socket closed)')
('Tick', 'discovery', LogLevel.INFO, 'Discovery(wss://localhost/omni/discovery): Auth::Credentials search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(wss://localhost/omni/discovery): Auth::Tokens search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(wss://localhost/omni/discovery): Auth::DeviceFlow search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(wss://localhost/omni/discovery): Api::Connection search failed: Connection is terminated')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(localhost): Completed')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(localhost): Stopping')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840B910 destroyed')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840CA40 destroyed')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F1A640 Sending CLOSE (reason=1000)')
('Tick', 'discovery', LogLevel.DEBUG, 'Discovery(localhost): Calling Callback')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Using username/password from environment variables for omniverse://localhost')
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'Starting')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840DE90 connecting to ws://127.0.0.1:3100')
('Tick', 'idl', LogLevel.VERBOSE, 'connecting to ws://127.0.0.1:3100/')
('Tick', 'idl', LogLevel.VERBOSE, '<< id=1 Credentials.auth 00000148A8785B78')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840DD00 destroyed')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F1F940 Sending CLOSE (reason=1000)')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F18980 Upgraded to WebSocket')
('Tick', 'idl', LogLevel.VERBOSE, '>> id=1 {"status": "OK", "version": 1, "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaXV5YW5nIiwicHJvZmlsZSI6eyJmaXJzdF9uYW1lIjoiWWFuZyIsImxhc3RfbmFtZSI6IkxpdSIsImVtYWlsIjoibGl1eUBudmlkaWEuY29tIiwiYWRtaW4iOmZhbHNlLCJudWNsZXVzX3JvIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJwcm92aWRlciI6IkludGVybmFsIiwiZW5hYmxlZCI6dHJ1ZSwiYWN0aXZhdGVkIjp0cnVlfSwianRpIjoiODdlZTkzN2IxOWE4NGNmNjk4ZGYyYjRiYzVmOGQyYTUiLCJpYXQiOjE3MDAyMTIzOTQsImV4cCI6MTcwMDI5ODc5NH0.InrTuqHpSTyM_VwkVyvh6LCUk2M1KPiZVANyZmgnTLMpIEA6XV316fxotq0Z5mBvH0NhmB_Gv4lEIDxgdZq4Sg", "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaXV5YW5nIiwicHJvZmlsZSI6eyJmaXJzdF9uYW1lIjoiWWFuZyIsImxhc3RfbmFtZSI6IkxpdSIsImVtYWlsIjoibGl1eUBudmlkaWEuY29tIiwiYWRtaW4iOmZhbHNlLCJudWNsZXVzX3JvIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJwcm92aWRlciI6IkludGVybmFsIiwiZW5hYmxlZCI6dHJ1ZSwiYWN0aXZhdGVkIjp0cnVlfSwianRpIjoiODcwYmU0NzYzMDZkNGQwN2EzYzM3ODBhYTM2YTljNTQiLCJpYXQiOjE3MDAyMTIzOTQsImV4cCI6MTcwMjgwNDM5NH0.C53uRByUT-JDZ7VSqvHuequRdF9DdMNefHNl-AHdAqpYkukZQ8rw93KvFD2pEMd3CyElvfZeGhjsUEuoYpYPZw", "username": "liuyang", "profile": {"first_name": "Yang", "last_name": "Liu", "email": "liuy@nvidia.com", "admin": false, "provider": "Internal", "readonly": false, "nucleus_ro": false, "enabled": true, "activated": true}}#')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Auth: Retrieved token for user "liuyang"')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '00000148A877E3D0 connecting to ws://127.0.0.1:3009')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, 'connecting to ws://127.0.0.1:3009/')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, 'Created connection 00000148A870AE10')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"client_capabilities":{"add_user_to_group":0,"auth":5,"authorize_token":4,"change_acl":0,"checkpoint_version":2,"copy":2,"copy2":2,"create":2,"create_asset":2,"create_asset_with_hash":2,"create_directory":1,"create_group":0,"create_object":2,"deep_copy_object_struct":0,"delete":0,"delete2":1,"get_acl":0,"get_acl_resolved":0,"get_acl_v2":0,"get_branches":1,"get_checkpoints":1,"get_group_users":0,"get_groups":0,"get_mount_info":0,"get_transaction_id":0,"get_user_groups":0,"get_users":0,"list":5,"list2":5,"lock":3,"mount":0,"ping":0,"read":2,"read_asset_resolved":0,"read_asset_version":0,"read_object_resolved":0,"read_object_version":0,"remove_group":0,"remove_user_from_group":0,"rename":2,"rename2":1,"rename_group":0,"replace_version":1,"service_resolve_acl":2,"service_subscribe_list":1,"set_acl_v2":0,"set_path_options":1,"set_path_options2":0,"set_user_agent":0,"stat2":2,"subscribe_list":4,"subscribe_read_asset":2,"subscribe_read_object":3,"subscribe_server_notifications":0,"unlock":2,"unmount":0,"update":1,"update_asset":2,"update_asset_with_hash":2,"update_object":2},"command":"authorize_token","id":1,"token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaXV5YW5nIiwicHJvZmlsZSI6eyJmaXJzdF9uYW1lIjoiWWFuZyIsImxhc3RfbmFtZSI6IkxpdSIsImVtYWlsIjoibGl1eUBudmlkaWEuY29tIiwiYWRtaW4iOmZhbHNlLCJudWNsZXVzX3JvIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJwcm92aWRlciI6IkludGVybmFsIiwiZW5hYmxlZCI6dHJ1ZSwiYWN0aXZhdGVkIjp0cnVlfSwianRpIjoiODdlZTkzN2IxOWE4NGNmNjk4ZGYyYjRiYzVmOGQyYTUiLCJpYXQiOjE3MDAyMTIzOTQsImV4cCI6MTcwMDI5ODc5NH0.InrTuqHpSTyM_VwkVyvh6LCUk2M1KPiZVANyZmgnTLMpIEA6XV316fxotq0Z5mBvH0NhmB_Gv4lEIDxgdZq4Sg","version":"1.19"}')
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'Stopping')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A840DE90 destroyed')
('Tick', 'idl', LogLevel.VERBOSE, '00000148A6F18980 Sending CLOSE (reason=1000)')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '00000148A6F19DA0 Upgraded to WebSocket')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"OK","server_capabilities":{"add_user_to_group":0,"auth":5,"authorize_token":4,"change_acl":0,"checkpoint_version":2,"copy":2,"copy2":2,"create":2,"create_asset":2,"create_asset_with_hash":2,"create_directory":1,"create_group":0,"create_object":2,"deep_copy_object_struct":0,"delete":0,"delete2":1,"get_acl":0,"get_acl_resolved":0,"get_acl_v2":0,"get_branches":1,"get_checkpoints":1,"get_group_users":0,"get_groups":0,"get_mount_info":0,"get_transaction_id":0,"get_user_groups":0,"get_users":0,"list":5,"list2":5,"lock":3,"mount":0,"ping":0,"read":2,"read_asset_resolved":0,"read_asset_version":0,"read_object_resolved":0,"read_object_version":0,"remove_group":0,"remove_user_from_group":0,"rename":2,"rename2":1,"rename_group":0,"replace_version":1,"service_resolve_acl":2,"service_subscribe_list":1,"set_acl_v2":0,"set_path_options":1,"set_path_options2":0,"set_user_agent":0,"stat2":2,"subscribe_list":4,"subscribe_read_asset":2,"subscribe_read_object":3,"subscribe_server_notifications":0,"unlock":2,"unmount":0,"update":1,"update_asset":2,"update_asset_with_hash":2,"update_object":2},"ts":{"omni_server_out_ts":13333041520577259},"version":"\\"1.14.17-e45e53d7\\" ","username":"liuyang","token":"GPRFXNSFR5VJKRUG","connection_id":"CWCVTT8KX4KW7ZVI","connection_id_signature":"98b0b3254e2d53a220d4d6d6e6a4d56d5cae88ae03484c7dc002f29065b08aee","max_chunk_size":134217728,"lft_address":"http://127.0.0.1:3030","lft_threshold":65536,"super_user":false,"multipart_chunk_size":5242880,"max_in_flight_requests":0,"id":1}')
('Tick', 'provider_nucleus', LogLevel.VERBOSE, 'Connected to omniverse://localhost as liuyang')
('Tick', 'provider_nucleus', LogLevel.VERBOSE, 'Connection ID: CWCVTT8KX4KW7ZVI')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Server is running version 1.14.17-e45e53d7')
('Tick', 'provider_nucleus', LogLevel.VERBOSE, 'LFT Enabled. Threshold=64 KB, Server=http://127.0.0.1:3030')
('Tick', 'provider_nucleus', LogLevel.VERBOSE, 'Server supports { { "add_user_to_group", 0 }, { "auth", 5 }, { "authorize_token", 4 }, { "change_acl", 0 }, { "checkpoint_version", 2 }, { "copy", 2 }, { "copy2", 2 }, { "create", 2 }, { "create_asset", 2 }, { "create_asset_with_hash", 2 }, { "create_directory", 1 }, { "create_group", 0 }, { "create_object", 2 }, { "deep_copy_object_struct", 0 }, { "delete", 0 }, { "delete2", 1 }, { "get_acl", 0 }, { "get_acl_resolved", 0 }, { "get_acl_v2", 0 }, { "get_branches", 1 }, { "get_checkpoints", 1 }, { "get_group_users", 0 }, { "get_groups", 0 }, { "get_mount_info", 0 }, { "get_transaction_id", 0 }, { "get_user_groups", 0 }, { "get_users", 0 }, { "list", 5 }, { "list2", 5 }, { "lock", 3 }, { "mount", 0 }, { "ping", 0 }, { "read", 2 }, { "read_asset_resolved", 0 }, { "read_asset_version", 0 }, { "read_object_resolved", 0 }, { "read_object_version", 0 }, { "remove_group", 0 }, { "remove_user_from_group", 0 }, { "rename", 2 }, { "rename2", 1 }, { "rename_group", 0 }, { "replace_version", 1 }, { "service_resolve_acl", 2 }, { "service_subscribe_list", 1 }, { "set_acl_v2", 0 }, { "set_path_options", 1 }, { "set_path_options2", 0 }, { "set_user_agent", 0 }, { "stat2", 2 }, { "subscribe_list", 4 }, { "subscribe_read_asset", 2 }, { "subscribe_read_object", 3 }, { "subscribe_server_notifications", 0 }, { "unlock", 2 }, { "unmount", 0 }, { "update", 1 }, { "update_asset", 2 }, { "update_asset_with_hash", 2 }, { "update_object", 2 } }')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Server omniverse://localhost supports atomic checkpoints')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"omni_objects2","id":2}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"versioning","id":3}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"OK","enabled":true,"id":3}')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Server omniverse://localhost supports checkpoints and it is enabled')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"OK","ext_value_min_size":262144,"id":2}')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Server omniverse://localhost supports omni-objects and it is enabled')
('Tick', 'provider_nucleus', LogLevel.INFO, 'Connected to omniverse://localhost')
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'ListCache miss! omniverse://localhost/Users/liuyang/iot-samples/')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"subscribe_list","id":4,"path":{"branch":"","path":"/Users/liuyang/iot-samples/"}}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"list2","id":5,"path":"/Users/liuyang/iot-samples/"}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"LATEST","id":4}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"OK","ts":{"omni_server_out_ts":13333041520580409},"entries":[{"path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/","branch":"default","acl":["admin","write","read"],"created_timestamp":1700212039,"modified_timestamp":1700212039,"path_type":"folder","empty":false,"mounted":false,"created_by":"liuyang","modified_by":"liuyang"}],"id":5}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"DONE","ts":{"omni_server_out_ts":13333041520580449},"id":5}')
('Tick', 'core', LogLevel.VERBOSE, 'Request 1: Stat(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01) returned Ok')
('Tick', 'core', LogLevel.VERBOSE, 'Request 1: copy(file:C:\\Users\\liuy\\Desktop\\IOTSample\\iot-samples-main\\content/ConveyorBelt_A08_PR_NVD_01 => omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01) returned Error: Already Exists')
('Main', 'core', LogLevel.VERBOSE, 'Request 5: resolve(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd)')
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'ListCache miss! omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"subscribe_list","id":6,"path":{"branch":"","path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/"}}')('Tick', 'nucleus_connection', LogLevel.VERBOSE, '<< {"command":"list2","id":7,"path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/"}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"LATEST","id":6}')
('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"OK","ts":{"omni_server_out_ts":13333041520596958},"entries":[{"path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/.thumbs/","branch":"default","acl":["admin","write","read"],"created_timestamp":1700212039,"modified_timestamp":1700212039,"path_type":"folder","empty":false,"mounted":false,"created_by":"liuyang","modified_by":"liuyang"},{"path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd","branch":"default","etag":"1","acl":["admin","write","read"],"created_timestamp":1700212039,"modified_timestamp":1700212039,"path_type":"asset","size":133,"empty":false,"mounted":false,"created_by":"liuyang","modified_by":"liuyang","hash_type":"sha-256-flat","hash_value":"5c27f098c9acccb345ca357904455771bd1fdbdc90e8eba7614bd6bfc8fe24d9","hash_bsize":1048576,"checkpointed":true,"transaction_id":395,"checkpoint_count":1},{"path":"/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/Materials/","branch":"default","acl":["admin","write","read"],"created_timestamp":1700212039,"modified_timestamp":1700212039,"path_type":"folder","empty":false,"mounted":false,"created_by":"liuyang","modified_by":"liuyang"}],"id":7}')('Tick', 'nucleus_connection', LogLevel.VERBOSE, '>> {"status":"DONE","ts":{"omni_server_out_ts":13333041520596980},"id":7}')
('Tick', 'core', LogLevel.VERBOSE, 'Request 5: resolve(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd): Found omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd')
('Main', 'core', LogLevel.VERBOSE, 'Request 8: resolve(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd)')
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'ListCache hit! omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/')
('Tick', 'core', LogLevel.VERBOSE, 'Request 8: resolve(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd): Found omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd')
('Main', 'core', LogLevel.VERBOSE, 'Request 10: getLocalFile(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd)')      
('Tick', 'provider_nucleus', LogLevel.DEBUG, 'ListCache hit! omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/')
('Tick', 'core', LogLevel.VERBOSE, 'Request 10: getLocalFile: omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd already exists as C:\\OmniVerse\\cache\\client\\omniverse\\5c27f098c9acccb345ca357904455771bd1fdbdc90e8eba7614bd6bfc8fe24d9.usd, not downloading')
('Tick', 'core', LogLevel.VERBOSE, 'Request 10: getLocalFile(omniverse://localhost/Users/liuyang/iot-samples/ConveyorBelt_A08_PR_NVD_01/ConveyorBelt_A08_PR_NVD_01.usd): Ok C:\\OmniVerse\\cache\\client\\omniverse\\5c27f098c9acccb345ca357904455771bd1fdbdc90e8eba7614bd6bfc8fe24d9.usd')
('File IO', 'provider_file', LogLevel.VERBOSE, 'GetFileAttributesExW() returned "The system cannot find the path specified."')

**Comment by ly01325** [comment]
ConveyorBelt_A08_PR_NVD_01.usd, 
It seems I missed this USD file , Is this problem related to Downloading ?,
Thanks

**Comment by fuocor** [comment]
If you open nucleus explorer and navigate to the destination folder, is it visible?

**Comment by ly01325** [comment]
![image](https://github.com/NVIDIA-Omniverse/iot-samples/assets/102361585/183e4945-e42b-4e6e-9fc6-b0f1607dd8a6)
No, So I think it is a downloading problem..Do you know where I can download this USD file?

**Comment by fuocor** [comment]
did you install fit-lfs before cloning the repo?
check the `./content/` folder and all the usd assets should be there.

If you did not install git-lfs, the easiest fix is to delete your local version, install it, and clone the repo again.

**Comment by ly01325** [comment]
Hi, I find the .usd file in the ./content/, And I move it manually to the omniverse://<nucleus server>/users/<user name>/iot-samples/ConveyorBelt_A08_PR_NVD_01/,, now it ran successfully, Thnaks.
my python version is 3.10.4
OS: Windows 10 Enterprise
